name: MacOS Workflow
on: [push, workflow_dispatch]

jobs:
  test:
    name: test on macos
    runs-on: macos-latest
    steps:
    - shell: bash
      run: |
        system_profiler SPSoftwareDataType SPHardwareDataType
